"""Nuevos campos en students model: emergency_contact_name, emergency_contact_phone y photo_url

Revision ID: 2e6e12ab2af4
Revises: 3fda168627d5
Create Date: 2026-04-15 13:23:34.030583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6e12ab2af4'
down_revision: Union[str, None] = '3fda168627d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')

    # ### end Alembic commands ###
